services:
  # Main Node.js API Service
  - type: web
    name: khronos-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Use external MongoDB Atlas (set this manually in dashboard)
      - key: MONGODB_URI
        value: your-mongodb-connection-string-here
      # Redis connection using connection string (more reliable)
      - key: REDIS_URL
        fromService:
          type: redis
          name: khronos-redis
          property: connectionString
      # Individual Redis components as backup
      - key: REDIS_HOST
        fromService:
          type: redis
          name: khronos-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: khronos-redis
          property: port
      - key: REDIS_PASSWORD
        value: ''
      # Add your other environment variables here
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com
      - key: CORS_URL
        value: https://your-frontend-domain.com

  # Redis Cache Service
  - type: redis
    name: khronos-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
